list(include('endpoint'))
---
endpoint:
  endpoint: str(matches='^(http|https)://.*', ignore_case=True)
  format: str(matches='^(era|era1|e2ss|e2hs|erb)$', ignore_case=True)
  name: str()
  torrent: bool(required=False)
  contacts: list(include('contact'), min=0, max=5, required=False)
  notes: list(include('contact'), min=0, max=5, required=False)

contact:
  name: str()
  link: str(required=False)

note:
  name: str()
  link: str(required=False)
