name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make pandoc texlive texlive-xetex texlive-fonts-recommended texlive-plain-generic build-essential curl libffi-dev libffi8ubuntu1 libgmp-dev libgmp10 libncurses-dev
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
          cabal install pandoc-sidenote
      - name: Run Makefile
        run: make
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/
